$cd "C:\Users\Matt\Desktop\decompiler\"
$modelname "Teh_Maestro\EU_Gunship_mini.mdl"
$model "studio" "eugunshipref.smd"

$cdmaterials "Teh_Maestro\"
$cdmaterials "Teh_Maestro\"
$hboxset "default"
$hbox 0 "DrawCall_0067" -26.073  -8.394  0.000  31.058  9.996  20.110
$surfaceprop "metal"
$keyvalues  { prop_data { "base" "Metal.Large"  } } 
$illumposition -0.051 -0.805 7.610
$sequence idle "idle" fps 1.00
