$cd "C:\Users\Matt\Desktop\decompiler\"
$modelname "Teh_Maestro\PAC_Gunship.mdl"
$model "studio" "pacgunshipref.smd"

$cdmaterials "Teh_Maestro\"
$cdmaterials "Teh_Maestro\"
$hboxset "default"
$hbox 0 "smdimport" -109.795  -256.483  0.000  107.518  309.741  115.422
$surfaceprop "metal"
$keyvalues  { prop_data { "base" "Metal.Large"  } } 
$illumposition 10.350 -1.139 57.711
$sequence idle "idle" fps 1.00
