$cd "C:\Users\Matt\Desktop\decompiler\"
$modelname "Teh_Maestro\EU_Gunship.mdl"
$model "studio" "eugunshipref.smd"

$cdmaterials "Teh_Maestro\"
$cdmaterials "Teh_Maestro\"
$hboxset "default"
$hbox 0 "DrawCall_0067" -260.732  -83.939  0.000  310.580  99.962  201.096
$surfaceprop "metal"
$keyvalues  { prop_data { "base" "Metal.Large"  } } 
$illumposition -0.507 -8.051 76.101
$sequence idle "idle" fps 1.00
