$cd "C:\Users\Matt\Desktop\decompiler\"
$modelname "Teh_Maestro\PAC_Gunship_mini.mdl"
$model "studio" "pacgunshipref.smd"

$cdmaterials "Teh_Maestro\"
$cdmaterials "Teh_Maestro\"
$hboxset "default"
$hbox 0 "smdimport" -10.979  -25.648  0.000  10.752  30.974  11.542
$surfaceprop "metal"
$keyvalues  { prop_data { "base" "Metal.Large"  } } 
$illumposition 1.035 -0.114 5.771
$sequence idle "idle" fps 1.00
